ZZOMING-K/2024_Algorithm_Study

- kichan/README.md
- kichan 브랜치 생성
- kichan 폴더 생성
- readme.md 생성
> Add README file for kichan's algorithm

- minkyeong/week1/10610_30.py
- minkyeong/week1/11399_ATM.py
- minkyeong/week1/1439_뒤집기.py
- minkyeong/week1/16435_스네이크버드.py
- minkyeong/week1/18008_ReMorse.py
- minkyeong/week1/30018_타슈.py
1. 30018  - 타슈
영우는 자전거를 최소 몇번을 옮겨야하는지 구하는 문제였습니다.  단순하게 a_i 자전거 수가 b_i 자전거 수보다 클 경우 i 대여소에 a_i - b_i 만큼의 자전거 수가 필요한 것 입니다. 총 자전거 수는 동일하므로 각 대여소에 부족한 자전거 수를 구해주면 됩니다. 
2. 16435 - 스네이크버드
과일들을 먹어 늘릴 수 있는 최대길이를 구하기 위해서는  과일을 많이 먹어야 합니다. 
과일을 먹으면 길이가 늘어나므로 간단하게 과일 높이가 작은 길이 부터 정렬하여 풀이했습니다. 
3. 11399 - ATM
각 사람이 돈을 인출하는데 필요한 시간의 합의 최솟값을 구하기 위해서는 단순히 오름차순으로 돈을 인출하는데 필요한 시간을 정렬하여 합을 구하면 되는 문제였습니다. 
4. 1439 - 뒤집기 
우선은 연속된 숫자를 그룹으로 생각했습니다. 
1111001111 의 경우에는 1 0 1 -> 1그룹 2번, 0그룹 1번이고 그렇다면 0의 그룹을 한번만 뒤집으면 모든 숫자가 1이 되므로 1번만 뒤집으면 된다.  
최소로 뒤집는 횟수를 구하기 위해서는 그룹 수가 적은 횟수만큼 뒤집으면 됩니다. 
따라서 1 그룹을 count 할 때 '10' 을 count 하고, 0 그룹을 count 할 때 '01'을 count 해주었습니다. 또한 마지막 그룹을 알기 위해서 마지막 숫자 그룹에 +1을 처리를 진행해주었습니다.   
5. 10610 - 30
30의 배수가 되기 위해서는 10의 배수이면서 3의 배수여야 합니다. 
1) 10의 배수가 되기 위해서는 0으로 숫자가 끝나야 합니다. 
2) 3의 배수가 …
> [2024-04-30] 조민경 week1

- mingyu/week2/10026_적록색약.py
> [2024-05-12] mingyu week2

- kichan/week2/boj_12761.py
- kichan/week2/boj_6059.py
- kichan/week2/boj_6186.py
참고:
- [https://yonghee.io/baegjun-boj-4344-pyeonggyuneun-neomgessji/](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fyonghee.io%2Fbaegjun-boj-4344-pyeonggyuneun-neomgessji%2F)
- [https://jinho-study.tistory.com/909](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fjinho-study.tistory.com%2F909)
참고:
- [https://velog.io/@rkdalstn7221/%EB%B0%B1%EC%A4%80-12761-%EB%8F%8C%EB%8B%A4%EB%A6%AC](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fvelog.io%2F%40rkdalstn7221%2F%25EB%25B0%25B1%25EC%25A4%2580-12761-%25EB%258F%258C%25EB%258B%25A4%25EB%25A6%25AC)
블로그/gpt 많이 참고하면서 해도 어렵네요ㅠ
> [2024-05-12] 이기찬 week2

- seungah/week2/6186_BestGrass.py
겨우 몸져누웠던 몸을 이끌고 하는데도 한문제밖에 풀지 못했습니다....는 솔직히 핑계고 제 실력이 문제였던것같습니다. 문제 계속 풀때마다 PR날리겠습니다...
> [2024-05-12] 최승아 week2

- minkyeong/week4/14753_MultiMax.py
- minkyeong/week4/18110_solved.py
- minkyeong/week4/1931_회의실배정.py
- minkyeong/week4/2470_두용액.py
- minkyeong/week4/3273_두수의합.py
아직 풀이 못한 2문제가 있습니다. (2075 , 2470)   
해당 문제는 일요일까지 풀이해보도록 하겠습니다 🍀 .. 
2075 - 아이디어 X , 2470 - 시간초과 발생
> [2024-05-25] 조민경 week4

- mingyu/week5/11053_가장긴증가하는부분수열.py
- mingyu/week5/1149_RGB거리.py
- mingyu/week5/1912_연속합.py
- mingyu/week5/2565_전깃줄.py
- mingyu/week5/2579_계단오르기.py
- mingyu/week5/9461_파도반수열.py
2565_전깃줄과 1149_RGB거리는 도저히 모르겠어서 풀지 못하였습니다 ㅠㅠ
> [2024-06-01] 김민규 week5

- kichan/week5/1149.py
- kichan/week5/11503.py
- kichan/week5/1912.py
- kichan/week5/2579.py
- kichan/week5/9461.py
> [2024-06-02] 이기찬 week5

- seungah/week6/1389_케빈베이컨.py
- seungah/week6/1446_지름길.py
- seungah/week6/1753_최단경로.py
방향그래프 최단경로문제는 실패했습니다... 혹시 성공하면 다시 올리겠습니다
> [2024-06-08] 최승아 week6

- kichan/week6/1446.py
- kichan/week6/1753.py
1446번은 풀다가 실패했구요ㅠ
1753번은 아래 링크 강의 보면서 했습니다
https://www.youtube.com/watch?v=izYANwrHwvQ
어렵네요..
> [2024-06-10] 이기찬 week6

- minkyeong/week7/15658_연산지끼워넣기.py
- minkyeong/week7/16922_로마숫자만들기.py
- minkyeong/week7/6603_독일로또.py
[16922] 로마숫자만들기 [6603] 독일로또 풀이했습니다. 
재귀함수를 이용하여 풀이한건 2문제이고 나머지는 감도 잡히지 않습니다.. 
해설을 봐도 잘 이해가 안가서 push를 하지 않겠습니다. 
재귀 완벽히 이해한 줄 알았는데 아닌가봐요.. 백트래킹 풀면서 더 헷갈렸네요.
> [2024-06-24] 조민경 week7

- kichan/week7/16922.py
- kichan/week7/6603.py
> [2024-06-24] 이기찬 week7

- seungah/week7/10971_외판원순회2.py
- seungah/week7/15658_연산자끼워넣기2.py
- seungah/week7/16922_로마숫자만들기.py
- seungah/week7/2023_신기한 소수.py
- seungah/week7/6603_로또.py
> [2024-06-23] 최승아 week7

- kichan/week8/모음사전.py
- kichan/week8/모의고사.py
- kichan/week8/소수 찾기.py
- kichan/week8/전력망을 둘로 나누기.py
- kichan/week8/최소직사각형.py
- kichan/week8/카펫.py
- kichan/week8/피로도.py
> [2024-06-30] 이기찬 week8

- bong-woon/week8/Readme.md
- bong-woon/week8/모음사전.py
- bong-woon/week8/모의고사.py
- bong-woon/week8/소수찾기.py
- bong-woon/week8/최소직사각형.py
- bong-woon/week8/카펫.py
- bong-woon/week8/피로도.py
8주차 과제입니다. 전력망 문제는 아직 풀지 못했습니다..
> [2024-06-29] 백봉운 week8

- seungah/week8/모음사전.py
- seungah/week8/모의고사.py
- seungah/week8/소수찾기.py
- seungah/week8/최소직사각형.py
- seungah/week8/카펫.py
전력망 문제, 피로도 문제 실패했습니다... 그 이외에는 풀이 완료
> [2024-06-29] week8 최승아

- seungah/week9/Hindex.py
- seungah/week9/K번째수.py
> [2024-07-06] 최승아 week9

- bong-woon/week9/H-Index.py
- bong-woon/week9/K번째수.py
- bong-woon/week9/Readme.md
9주차 과제입니다. 가장 큰 수 문제가 생각보다 잘 안 풀리네요 ㅠ
조금 더 고민해보고 나중에 추가로 올리겠습니다
> [2024-07-06] 백봉운 week9

- mingyu/week9/H-Index.py
- mingyu/week9/K번째수.py
- mingyu/week9/가장큰수.py
> [2024-07-07] 김민규 week9

- minkyeong/week9/H-Index.py
- minkyeong/week9/K번쨰수.py
- minkyeong/week9/README.md
- minkyeong/week9/가장큰수.py
정렬문제 2,3번은 블로그 유랑하며 힌트를 얻은 코드 입니다.
> [2024-07-07] 조민경 week9

- kichan/week9/Hindex.py
- kichan/week9/k번째수.py
- kichan/week9/가장큰수.py
> [2024-07-08] 이기찬 week9

- mingyu/week10/같은숫자는싫어.py
- mingyu/week10/기능개발.py
- mingyu/week10/다리를지나는트럭.py
- mingyu/week10/올바른괄호.py
- mingyu/week10/주식가격.py
- mingyu/week10/프로세스.py
> [2024-07-14] 김민규 week10

- seungah/week10/같은숫자는싫어.py
- seungah/week10/기능개발.py
- seungah/week10/올바른괄호.py
- seungah/week10/주식가격.py
- seungah/week10/프로세스.py
프로세스는 풀긴 풀었지만 실패로 판단되고, 트럭 문제는 문제를 이해 못했습니다
> [2024-07-13] 최승아 week10

- kichan/week10/같은 숫자는 싫어.py
- kichan/week10/기능개발.py
- kichan/week10/다리를 지나는 트럭.py
- kichan/week10/올바른 괄호.py
- kichan/week10/주식가격.py
- kichan/week10/프로세스.py
> [2024-07-13] 이기찬 week10

- minkyeong/week10/README.md
- minkyeong/week10/같은숫자는싫어.py
- minkyeong/week10/기능개발.py
- minkyeong/week10/올바른괄호.py
- minkyeong/week10/주식가격.py
- minkyeong/week10/프로세스.py
주식가격 , 다리를 지나는 트럭 문제는 아직 해결하지 못했습니다. 이외 문제는 풀이했습니다. 
+ 주식가격 문제는 다른 풀이 보고 이해한 척 했습니다. ( 다시 마주하면 풀 수 있을 지 의문..입니다?)
> [2024-07-13] 조민경 week10 

- kichan/week11/베스트앨범.py
- kichan/week11/완주못한선수.py
- kichan/week11/의상.py
- kichan/week11/전화번호목록.py
- kichan/week11/포켓몬.py
> [2024-07-21] 이기찬 week11

- minkyeong/week11/README.md
- minkyeong/week11/베스트앨범.py
- minkyeong/week11/완주하지못한선수.py
- minkyeong/week11/의상.py
- minkyeong/week11/전화번호목록.py
- minkyeong/week11/포켓몬.py
- 전화번호 목록 문제는 다른 블로그를 참조해서 풀이한 문제입니다.
> [2024-07-21] 조민경 week11

- seungah/week11/완주하지 못한 선수.py
- seungah/week11/의상.py
- seungah/week11/전화번호 목록.py
- seungah/week11/폰켓몬.py
마지막 문제 실패, 어려운 문제는 도움을 많이 받았읍니다........
> [2024-07-20] week11 최승아

- bong-woon/week11/Readme.md
- bong-woon/week11/베스트앨범.py
- bong-woon/week11/완주하지 못한 선수.py
- bong-woon/week11/의상.py
- bong-woon/week11/전화번호 목록.py
- bong-woon/week11/폰켓몬.py
> [2024-07-20] 백봉운 week11

- kichan/week12/네트워크.py
- kichan/week12/타겟넘버.py
오랜만에 푸니까 어렵네요..
타겟넘버,네트워크 2문제..풀었습니다..
> [2024-08-12] 이기찬 week12

- minkyeong/week13/구명보트.py
- minkyeong/week13/조이스틱.py
- minkyeong/week13/체육복.py
- minkyeong/week13/큰수만들기.py
1. 구명보트, 체육복, 큰 수 만들기 풀이 완료
2. 조이스틱 (풀이했으나 통과 실패) 
3. 섬 연결하기, 단속 카메라 풀이 실패
> [2024-09-09] 조민경 week15

- mingyu/week13/더맵게.py
- mingyu/week13/이중우선순위큐.py
- mingyu/week14/구명보트.py
- mingyu/week14/단속카메라.py
- mingyu/week14/섬연결하기.py
- mingyu/week14/체육복.py
- mingyu/week14/큰수만들기.py
13 + 14주차 풀이입니다
13주차 디스크 컨트롤러 문제와 14주차 조이스틱 문제는 못 풀었습니다
> [2024-08-19] 김민규 week13 + week14

- kichan/week17/방문 길이.py
- kichan/week17/배달.py
- kichan/week17/소수 만들기
- kichan/week17/숫자게임.py
- kichan/week17/스킬트리.py
- kichan/week17/영어 끝말잇기.py
- kichan/week17/예산.py
- kichan/week17/점프와 순간이동.py
각 문제별로 힌트는 하나씩 찾아보면서 풀었던 것 같네용
> [2024-10-07] 이기찬 week17
